server:
  servlet:
    context-path: /spring-jpa
  port: 9090
management:
  server:
    port: 8081
    servlet:
      context-path: /spring-jpa
  endpoints:
    web:
      base-path: /

spring:
  datasource:
    driverClassName:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true